#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "MindForge production launch"

VERCEL_SCOPE="${VERCEL_SCOPE:-test11-ecf6}"
VERCEL_PROJECT="${VERCEL_PROJECT:-mind-forge}"
VERCEL_PROJECT_URL="https://vercel.com/${VERCEL_SCOPE}/${VERCEL_PROJECT}"
PRODUCTION_URL=""

require_value() {
  local name="$1" value="$2"
  [[ -n "$value" ]] || { warn "$name is required; re-run when you have it."; exit 1; }
}

set_vercel_env() {
  local name="$1" value="$2" visibility="${3:-sensitive}"
  [[ -n "$value" ]] || { note "skipped empty optional value: $name"; return; }
  local args=(env add "$name" production --force --yes)
  if [[ "$visibility" == "sensitive" ]]; then args+=(--sensitive); else args+=(--no-sensitive); fi
  if printf '%s' "$value" | npx --yes vercel@latest "${args[@]}" >/dev/null; then
    printf '  %s✓ set%s Vercel production variable %s\n' "$GREEN" "$RESET" "$name"
  else
    warn "could not set Vercel variable $name"
    exit 1
  fi
}

stage "Verify and link the Vercel project"
say "The repository is imported as ${VERCEL_SCOPE}/${VERCEL_PROJECT}."
open_url "$VERCEL_PROJECT_URL"
step "Confirm the project shows Shubham080802/MindForge."
step "Confirm Production Branch is main under Settings → Git."
pause "Return after both checks."
if confirm "Link this checkout to the Vercel project now?"; then
  npx --yes vercel@latest link --yes --project "$VERCEL_PROJECT" --team "$VERCEL_SCOPE"
else
  SKIPPED+=("Vercel CLI link")
fi

stage "Provision production PostgreSQL"
open_url "https://vercel.com/marketplace/prisma"
step "Add Prisma Postgres to mind-forge and finish provisioning."
step "Verify backup retention, restore access, and point-in-time recovery for the selected plan."
warn "Do not claim backup readiness until a restore drill succeeds."
step "Copy the pooled production DATABASE_URL."
ask_secret DATABASE_URL "Paste DATABASE_URL:"
require_value DATABASE_URL "$DATABASE_URL"
write_env DATABASE_URL "$DATABASE_URL"
pause "Confirm recovery settings are recorded."

stage "Provision distributed rate limiting"
open_url "https://vercel.com/marketplace/category/storage"
step "Add Upstash for Redis only to mind-forge."
step "Copy its REST URL and REST token."
ask UPSTASH_REDIS_REST_URL "Paste UPSTASH_REDIS_REST_URL:"
ask_secret UPSTASH_REDIS_REST_TOKEN "Paste UPSTASH_REDIS_REST_TOKEN:"
require_value UPSTASH_REDIS_REST_URL "$UPSTASH_REDIS_REST_URL"
require_value UPSTASH_REDIS_REST_TOKEN "$UPSTASH_REDIS_REST_TOKEN"
write_env UPSTASH_REDIS_REST_URL "$UPSTASH_REDIS_REST_URL"
write_env UPSTASH_REDIS_REST_TOKEN "$UPSTASH_REDIS_REST_TOKEN"

stage "Configure AI, email, and support"
open_url "https://platform.openai.com/api-keys"
step "Create a restricted production OpenAI key for MindForge."
ask_secret OPENAI_API_KEY "Paste OPENAI_API_KEY:"
require_value OPENAI_API_KEY "$OPENAI_API_KEY"
write_env OPENAI_API_KEY "$OPENAI_API_KEY"
open_url "https://resend.com/domains"
step "Verify the sending domain and SPF/DKIM, then create a production API key."
ask_secret EMAIL_SERVER_PASSWORD "Paste the Resend API key (SMTP password):"
ask EMAIL_FROM "Enter EMAIL_FROM, e.g. MindForge <hello@your-domain.com>:"
ask NEXT_PUBLIC_SUPPORT_EMAIL "Enter the monitored support email:"
require_value EMAIL_SERVER_PASSWORD "$EMAIL_SERVER_PASSWORD"
require_value EMAIL_FROM "$EMAIL_FROM"
require_value NEXT_PUBLIC_SUPPORT_EMAIL "$NEXT_PUBLIC_SUPPORT_EMAIL"
write_env EMAIL_SERVER_HOST "smtp.resend.com"
write_env EMAIL_SERVER_PORT "465"
write_env EMAIL_SERVER_SECURE "true"
write_env EMAIL_SERVER_USER "resend"
write_env EMAIL_SERVER_PASSWORD "$EMAIL_SERVER_PASSWORD"
write_env EMAIL_FROM "$EMAIL_FROM"
write_env NEXT_PUBLIC_SUPPORT_EMAIL "$NEXT_PUBLIC_SUPPORT_EMAIL"

stage "Configure domain, auth, retention, and monitoring"
open_url "${VERCEL_PROJECT_URL}/settings/domains"
step "Add the production domain and wait for Valid Configuration."
ask NEXTAUTH_URL "Enter the final HTTPS production URL (no trailing slash):"
require_value NEXTAUTH_URL "$NEXTAUTH_URL"
PRODUCTION_URL="${NEXTAUTH_URL%/}"
[[ "$PRODUCTION_URL" == https://* ]] || { warn "Production URL must use https://"; exit 1; }
write_env NEXTAUTH_URL "$PRODUCTION_URL"
NEXTAUTH_SECRET=$(_existing NEXTAUTH_SECRET || true)
[[ -n "$NEXTAUTH_SECRET" ]] || NEXTAUTH_SECRET=$(openssl rand -base64 48 | tr -d '\n')
CRON_SECRET=$(_existing CRON_SECRET || true)
[[ -n "$CRON_SECRET" ]] || CRON_SECRET=$(openssl rand -base64 48 | tr -d '\n')
write_env NEXTAUTH_SECRET "$NEXTAUTH_SECRET"
write_env CRON_SECRET "$CRON_SECRET"
write_env TRUSTED_PROXY_HEADER "x-forwarded-for"
write_env AUDIT_RETENTION_DAYS "365"
say "A monitoring webhook is optional; platform logs remain available when omitted."
ask ERROR_MONITORING_WEBHOOK_URL "Paste ERROR_MONITORING_WEBHOOK_URL, or Enter to omit:"
if [[ -n "$ERROR_MONITORING_WEBHOOK_URL" ]]; then
  ask_secret ERROR_MONITORING_WEBHOOK_TOKEN "Paste ERROR_MONITORING_WEBHOOK_TOKEN:"
  write_env ERROR_MONITORING_WEBHOOK_URL "$ERROR_MONITORING_WEBHOOK_URL"
  write_env ERROR_MONITORING_WEBHOOK_TOKEN "$ERROR_MONITORING_WEBHOOK_TOKEN"
fi
open_url "https://vercel.com/docs/alerts"
step "Alert on ${PRODUCTION_URL}/api/health, cron failures, and server errors."
pause "Return after domain and alert destinations are verified."

stage "Sync secrets, migrate, and deploy"
say "This transmits the collected credentials to the linked Vercel project."
confirm "Set production variables in Vercel now?" || exit 1
set_vercel_env DATABASE_URL "$DATABASE_URL"
set_vercel_env NEXTAUTH_URL "$PRODUCTION_URL" plain
set_vercel_env NEXTAUTH_SECRET "$NEXTAUTH_SECRET"
set_vercel_env OPENAI_API_KEY "$OPENAI_API_KEY"
set_vercel_env UPSTASH_REDIS_REST_URL "$UPSTASH_REDIS_REST_URL" plain
set_vercel_env UPSTASH_REDIS_REST_TOKEN "$UPSTASH_REDIS_REST_TOKEN"
set_vercel_env TRUSTED_PROXY_HEADER "x-forwarded-for" plain
set_vercel_env EMAIL_SERVER_HOST "smtp.resend.com" plain
set_vercel_env EMAIL_SERVER_PORT "465" plain
set_vercel_env EMAIL_SERVER_SECURE "true" plain
set_vercel_env EMAIL_SERVER_USER "resend" plain
set_vercel_env EMAIL_SERVER_PASSWORD "$EMAIL_SERVER_PASSWORD"
set_vercel_env EMAIL_FROM "$EMAIL_FROM" plain
set_vercel_env NEXT_PUBLIC_SUPPORT_EMAIL "$NEXT_PUBLIC_SUPPORT_EMAIL" plain
set_vercel_env CRON_SECRET "$CRON_SECRET"
set_vercel_env AUDIT_RETENTION_DAYS "365" plain
if [[ -n "$ERROR_MONITORING_WEBHOOK_URL" ]]; then
  set_vercel_env ERROR_MONITORING_WEBHOOK_URL "$ERROR_MONITORING_WEBHOOK_URL" plain
  set_vercel_env ERROR_MONITORING_WEBHOOK_TOKEN "$ERROR_MONITORING_WEBHOOK_TOKEN"
fi
if confirm "Apply migrations and create the production deployment?"; then
  npx --yes vercel@latest env run -e production -- corepack pnpm prisma migrate deploy
  npx --yes vercel@latest deploy --prod --yes
else
  SKIPPED+=("production migration and deployment")
fi
step "Verify sign-up, email verification, sign-in, upload, quiz generation, and sign-out."
pause "Return after the production journey works."

stage "Run E2E and record operational sign-off"
ask E2E_EMAIL "Disposable verified E2E learner email:"
ask_secret E2E_PASSWORD "Disposable E2E learner password:"
require_value E2E_EMAIL "$E2E_EMAIL"
require_value E2E_PASSWORD "$E2E_PASSWORD"
set_secret E2E_EMAIL "$E2E_EMAIL"
set_secret E2E_PASSWORD "$E2E_PASSWORD"
set_var STAGING_BASE_URL "$PRODUCTION_URL"
if confirm "Run destructive staging E2E against $PRODUCTION_URL now?"; then
  PLAYWRIGHT_BASE_URL="$PRODUCTION_URL" E2E_EMAIL="$E2E_EMAIL" E2E_PASSWORD="$E2E_PASSWORD" corepack pnpm test:e2e:staging
else
  SKIPPED+=("staging E2E test")
fi
say "Assign accountable humans; this records ownership, not legal approval."
ask LEGAL_APPROVER "Privacy/terms reviewer:"
ask INCIDENT_OWNER "Incident and rollback owner:"
ask SUPPORT_OWNER "Support mailbox owner:"
mkdir -p ops
{
  printf '# Local launch sign-off\n\n'
  printf -- '- Production URL: %s\n' "$PRODUCTION_URL"
  printf -- '- Privacy/terms reviewer: %s\n' "$LEGAL_APPROVER"
  printf -- '- Incident and rollback owner: %s\n' "$INCIDENT_OWNER"
  printf -- '- Support mailbox owner: %s\n' "$SUPPORT_OWNER"
  printf -- '- Recorded (UTC): %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '\nThis is not a substitute for legal review, a tested restore, or an incident drill.\n'
} > ops/launch-signoff.local.md
note "recorded ops/launch-signoff.local.md"
open_url "${PRODUCTION_URL}/privacy"
step "Approve privacy/terms, run a restore drill, and exercise rollback."
pause "Press Enter when remaining evidence has an owner and due date."

finish
